apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bug-web
  template:
    metadata:
      labels:
        app: bug-web
    spec:
      containers:
      - name: bug-web
        image: ghcr.io/Shibasan7/bug-guess-game:latest
        ports:
        - containerPort: 5000

        env:
        - name: OLLAMA_HOST
          value: "http://ollama:11434"

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        
        startupProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 30
          periodSeconds: 5